# Generated by Django 3.1.1 on 2020-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_apps', '0003_profile_useranalytic_vicethreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apps',
        ),
        migrations.AddField(
            model_name='profile',
            name='apps',
            field=models.ManyToManyField(related_name='profile', to='open_apps.App'),
        ),
    ]
