# Generated by Django 3.1.1 on 2021-01-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_apps', '0004_auto_20201217_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
