# Generated by Django 3.1.1 on 2021-01-06 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_apps', '0005_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vicethreshold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vicethresholds', to=settings.AUTH_USER_MODEL),
        ),
    ]
