# Generated by Django 3.1.1 on 2021-01-09 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_apps', '0006_auto_20210106_0947'),
    ]

    operations = [
        migrations.RenameModel(old_name="ViceThreshold",
                               new_name="UserAnalyticThreshold"),
        migrations.AlterField(
            model_name='useranalyticthreshold',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useranalyticthreshold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='useranalyticthresholds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranalytic',
            name='threshold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='useranalytics', to='open_apps.useranalyticthreshold'),
        ),
        migrations.CreateModel(
            name='Vice',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='vices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViceThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('threshold', models.IntegerField(default=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='vicethresholds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViceAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='viceanalytics', to='open_apps.vicethreshold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='viceanalytics', to=settings.AUTH_USER_MODEL)),
                ('vice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='viceanalytics', to='open_apps.vice')),
            ],
        ),
    ]
