# Generated by Django 3.1.1 on 2021-01-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_apps', '0007_auto_20210109_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viceanalytic',
            name='threshold',
        ),
        migrations.DeleteModel(
            name='ViceThreshold',
        ),
    ]
