# Generated by Django 3.1.1 on 2021-01-29 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_apps', '0008_auto_20210128_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='viceanalytic',
            name='time_between',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
