# Generated by Django 3.1.1 on 2021-01-30 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_apps', '0009_viceanalytic_time_between'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viceanalytic',
            name='time_between',
        ),
        migrations.AddField(
            model_name='vice',
            name='time_between',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
    ]
