# Generated by Django 3.1.1 on 2021-04-17 02:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_apps', '0011_savedpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTimeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracktimename', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('track_time_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracktime', to='open_apps.tracktimename')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracktime', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTrackerPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_pomodoro', models.BooleanField(default=True)),
                ('pomodoro_interval_time', models.TimeField(default=datetime.time(0, 25))),
                ('break_interval_time', models.TimeField(default=datetime.time(0, 5))),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_apps.profile')),
            ],
        ),
    ]
