# Generated by Django 3.1.1 on 2021-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_apps', '0013_auto_20210510_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktime',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tracktimename',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
