# Generated by Django 3.1.1 on 2020-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_auto_20200922_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(),
        ),
    ]
