# Generated by Django 3.1.1 on 2020-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_auto_20201026_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='weekdays',
            field=models.TextField(default='Sun,Mon,Tue,Wed,Thu,Fri,Sat'),
        ),
    ]
