# Generated by Django 3.1.1 on 2020-11-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_saver', '0005_auto_20200923_1935'),
    ]

    database_operations = [
        migrations.AlterModelTable(name="Post", table="open_apps_post"),
        migrations.AlterModelTable(
            name="SavedPost", table="open_apps_savedpost"),
        migrations.AlterModelTable(name="Title", table="open_apps_title"),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations)
    ]
