# Generated by Django 3.1.1 on 2020-11-03 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firebase_auth', '0002_useranalytic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalytic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useranalytics', to=settings.AUTH_USER_MODEL),
        ),
    ]
