# Generated by Django 3.1.1 on 2020-11-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0005_auto_20201107_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vicethreshold',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
